"""
    Crossly Buyer API

    The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from crossly_buyer.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from crossly_buyer.exceptions import ApiAttributeError


def lazy_import():
    from crossly_buyer.model.get_analytic_dashboard_response_avg_sale_price_by_platform import GetAnalyticDashboardResponseAvgSalePriceByPlatform
    from crossly_buyer.model.get_analytic_dashboard_response_cancel_rate import GetAnalyticDashboardResponseCancelRate
    from crossly_buyer.model.get_analytic_dashboard_response_recent_sales import GetAnalyticDashboardResponseRecentSales
    from crossly_buyer.model.get_analytic_dashboard_response_revenue import GetAnalyticDashboardResponseRevenue
    from crossly_buyer.model.get_analytic_dashboard_response_revenue_by_day import GetAnalyticDashboardResponseRevenueByDay
    from crossly_buyer.model.get_analytic_dashboard_response_sales_by_platform import GetAnalyticDashboardResponseSalesByPlatform
    from crossly_buyer.model.get_analytic_dashboard_response_sell_through import GetAnalyticDashboardResponseSellThrough
    from crossly_buyer.model.get_analytic_dashboard_response_top5_items_by_revenue import GetAnalyticDashboardResponseTop5ItemsByRevenue
    from crossly_buyer.model.get_analytic_dashboard_response_top_categories import GetAnalyticDashboardResponseTopCategories
    globals()['GetAnalyticDashboardResponseAvgSalePriceByPlatform'] = GetAnalyticDashboardResponseAvgSalePriceByPlatform
    globals()['GetAnalyticDashboardResponseCancelRate'] = GetAnalyticDashboardResponseCancelRate
    globals()['GetAnalyticDashboardResponseRecentSales'] = GetAnalyticDashboardResponseRecentSales
    globals()['GetAnalyticDashboardResponseRevenue'] = GetAnalyticDashboardResponseRevenue
    globals()['GetAnalyticDashboardResponseRevenueByDay'] = GetAnalyticDashboardResponseRevenueByDay
    globals()['GetAnalyticDashboardResponseSalesByPlatform'] = GetAnalyticDashboardResponseSalesByPlatform
    globals()['GetAnalyticDashboardResponseSellThrough'] = GetAnalyticDashboardResponseSellThrough
    globals()['GetAnalyticDashboardResponseTop5ItemsByRevenue'] = GetAnalyticDashboardResponseTop5ItemsByRevenue
    globals()['GetAnalyticDashboardResponseTopCategories'] = GetAnalyticDashboardResponseTopCategories


class GetAnalyticDashboardResponse(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'revenue': (GetAnalyticDashboardResponseRevenue,),  # noqa: E501
            'profit': (GetAnalyticDashboardResponseRevenue,),  # noqa: E501
            'sold_items_count': (GetAnalyticDashboardResponseRevenue,),  # noqa: E501
            'cancelled_count': (GetAnalyticDashboardResponseRevenue,),  # noqa: E501
            'cancel_rate': (GetAnalyticDashboardResponseCancelRate,),  # noqa: E501
            'refunded_amount': (GetAnalyticDashboardResponseRevenue,),  # noqa: E501
            'refunded_count': (GetAnalyticDashboardResponseRevenue,),  # noqa: E501
            'listed_items_count': (GetAnalyticDashboardResponseRevenue,),  # noqa: E501
            'avg_sale_price': (GetAnalyticDashboardResponseRevenue,),  # noqa: E501
            'sell_through': (GetAnalyticDashboardResponseSellThrough,),  # noqa: E501
            'sales_by_platform': ([GetAnalyticDashboardResponseSalesByPlatform],),  # noqa: E501
            'avg_sale_price_by_platform': ([GetAnalyticDashboardResponseAvgSalePriceByPlatform],),  # noqa: E501
            'revenue_by_day': ([GetAnalyticDashboardResponseRevenueByDay],),  # noqa: E501
            'top_categories': ([GetAnalyticDashboardResponseTopCategories],),  # noqa: E501
            'top_subcategories': ([GetAnalyticDashboardResponseTopCategories],),  # noqa: E501
            'top_brands': ([GetAnalyticDashboardResponseTopCategories],),  # noqa: E501
            'top5_items_by_revenue': ([GetAnalyticDashboardResponseTop5ItemsByRevenue],),  # noqa: E501
            'recent_sales': ([GetAnalyticDashboardResponseRecentSales],),  # noqa: E501
            'available_labels': ([str],),  # noqa: E501
            'sell_through_rate': (float, none_type,),  # noqa: E501
            'avg_days_to_sell': (float, none_type,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'revenue': 'revenue',  # noqa: E501
        'profit': 'profit',  # noqa: E501
        'sold_items_count': 'soldItemsCount',  # noqa: E501
        'cancelled_count': 'cancelledCount',  # noqa: E501
        'cancel_rate': 'cancelRate',  # noqa: E501
        'refunded_amount': 'refundedAmount',  # noqa: E501
        'refunded_count': 'refundedCount',  # noqa: E501
        'listed_items_count': 'listedItemsCount',  # noqa: E501
        'avg_sale_price': 'avgSalePrice',  # noqa: E501
        'sell_through': 'sellThrough',  # noqa: E501
        'sales_by_platform': 'salesByPlatform',  # noqa: E501
        'avg_sale_price_by_platform': 'avgSalePriceByPlatform',  # noqa: E501
        'revenue_by_day': 'revenueByDay',  # noqa: E501
        'top_categories': 'topCategories',  # noqa: E501
        'top_subcategories': 'topSubcategories',  # noqa: E501
        'top_brands': 'topBrands',  # noqa: E501
        'top5_items_by_revenue': 'top5ItemsByRevenue',  # noqa: E501
        'recent_sales': 'recentSales',  # noqa: E501
        'available_labels': 'availableLabels',  # noqa: E501
        'sell_through_rate': 'sellThroughRate',  # noqa: E501
        'avg_days_to_sell': 'avgDaysToSell',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, revenue, profit, sold_items_count, cancelled_count, cancel_rate, refunded_amount, refunded_count, listed_items_count, avg_sale_price, sell_through, sales_by_platform, avg_sale_price_by_platform, revenue_by_day, top_categories, top_subcategories, top_brands, top5_items_by_revenue, recent_sales, available_labels, *args, **kwargs):  # noqa: E501
        """GetAnalyticDashboardResponse - a model defined in OpenAPI

        Args:
            revenue (GetAnalyticDashboardResponseRevenue):
            profit (GetAnalyticDashboardResponseRevenue):
            sold_items_count (GetAnalyticDashboardResponseRevenue):
            cancelled_count (GetAnalyticDashboardResponseRevenue):
            cancel_rate (GetAnalyticDashboardResponseCancelRate):
            refunded_amount (GetAnalyticDashboardResponseRevenue):
            refunded_count (GetAnalyticDashboardResponseRevenue):
            listed_items_count (GetAnalyticDashboardResponseRevenue):
            avg_sale_price (GetAnalyticDashboardResponseRevenue):
            sell_through (GetAnalyticDashboardResponseSellThrough):
            sales_by_platform ([GetAnalyticDashboardResponseSalesByPlatform]):
            avg_sale_price_by_platform ([GetAnalyticDashboardResponseAvgSalePriceByPlatform]):
            revenue_by_day ([GetAnalyticDashboardResponseRevenueByDay]):
            top_categories ([GetAnalyticDashboardResponseTopCategories]):
            top_subcategories ([GetAnalyticDashboardResponseTopCategories]):
            top_brands ([GetAnalyticDashboardResponseTopCategories]):
            top5_items_by_revenue ([GetAnalyticDashboardResponseTop5ItemsByRevenue]):
            recent_sales ([GetAnalyticDashboardResponseRecentSales]):
            available_labels ([str]):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            sell_through_rate (float, none_type): [optional]  # noqa: E501
            avg_days_to_sell (float, none_type): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.revenue = revenue
        self.profit = profit
        self.sold_items_count = sold_items_count
        self.cancelled_count = cancelled_count
        self.cancel_rate = cancel_rate
        self.refunded_amount = refunded_amount
        self.refunded_count = refunded_count
        self.listed_items_count = listed_items_count
        self.avg_sale_price = avg_sale_price
        self.sell_through = sell_through
        self.sales_by_platform = sales_by_platform
        self.avg_sale_price_by_platform = avg_sale_price_by_platform
        self.revenue_by_day = revenue_by_day
        self.top_categories = top_categories
        self.top_subcategories = top_subcategories
        self.top_brands = top_brands
        self.top5_items_by_revenue = top5_items_by_revenue
        self.recent_sales = recent_sales
        self.available_labels = available_labels
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, revenue, profit, sold_items_count, cancelled_count, cancel_rate, refunded_amount, refunded_count, listed_items_count, avg_sale_price, sell_through, sales_by_platform, avg_sale_price_by_platform, revenue_by_day, top_categories, top_subcategories, top_brands, top5_items_by_revenue, recent_sales, available_labels, *args, **kwargs):  # noqa: E501
        """GetAnalyticDashboardResponse - a model defined in OpenAPI

        Args:
            revenue (GetAnalyticDashboardResponseRevenue):
            profit (GetAnalyticDashboardResponseRevenue):
            sold_items_count (GetAnalyticDashboardResponseRevenue):
            cancelled_count (GetAnalyticDashboardResponseRevenue):
            cancel_rate (GetAnalyticDashboardResponseCancelRate):
            refunded_amount (GetAnalyticDashboardResponseRevenue):
            refunded_count (GetAnalyticDashboardResponseRevenue):
            listed_items_count (GetAnalyticDashboardResponseRevenue):
            avg_sale_price (GetAnalyticDashboardResponseRevenue):
            sell_through (GetAnalyticDashboardResponseSellThrough):
            sales_by_platform ([GetAnalyticDashboardResponseSalesByPlatform]):
            avg_sale_price_by_platform ([GetAnalyticDashboardResponseAvgSalePriceByPlatform]):
            revenue_by_day ([GetAnalyticDashboardResponseRevenueByDay]):
            top_categories ([GetAnalyticDashboardResponseTopCategories]):
            top_subcategories ([GetAnalyticDashboardResponseTopCategories]):
            top_brands ([GetAnalyticDashboardResponseTopCategories]):
            top5_items_by_revenue ([GetAnalyticDashboardResponseTop5ItemsByRevenue]):
            recent_sales ([GetAnalyticDashboardResponseRecentSales]):
            available_labels ([str]):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            sell_through_rate (float, none_type): [optional]  # noqa: E501
            avg_days_to_sell (float, none_type): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.revenue = revenue
        self.profit = profit
        self.sold_items_count = sold_items_count
        self.cancelled_count = cancelled_count
        self.cancel_rate = cancel_rate
        self.refunded_amount = refunded_amount
        self.refunded_count = refunded_count
        self.listed_items_count = listed_items_count
        self.avg_sale_price = avg_sale_price
        self.sell_through = sell_through
        self.sales_by_platform = sales_by_platform
        self.avg_sale_price_by_platform = avg_sale_price_by_platform
        self.revenue_by_day = revenue_by_day
        self.top_categories = top_categories
        self.top_subcategories = top_subcategories
        self.top_brands = top_brands
        self.top5_items_by_revenue = top5_items_by_revenue
        self.recent_sales = recent_sales
        self.available_labels = available_labels
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
