"""
    Crossly Buyer API

    The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from crossly_buyer.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from crossly_buyer.exceptions import ApiAttributeError


def lazy_import():
    from crossly_buyer.model.list_orders_item_tracking_history import ListOrdersItemTrackingHistory
    globals()['ListOrdersItemTrackingHistory'] = ListOrdersItemTrackingHistory


class GetOrderResponse(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'id': (str,),  # noqa: E501
            'created_at': (datetime,),  # noqa: E501
            'updated_at': (datetime,),  # noqa: E501
            'user_id': (str,),  # noqa: E501
            'quantity': (float,),  # noqa: E501
            'status': (str,),  # noqa: E501
            'platform': (str,),  # noqa: E501
            'sales_channel': (str,),  # noqa: E501
            'oversold_by': (float,),  # noqa: E501
            'is_disputed': (bool,),  # noqa: E501
            'arrival_condition_photos': ([str],),  # noqa: E501
            'fulfillment_method': (str,),  # noqa: E501
            'notes': (str, none_type,),  # noqa: E501
            'cancelled_at': (datetime, none_type,),  # noqa: E501
            'listing_id': (str, none_type,),  # noqa: E501
            'inventory_item_id': (str, none_type,),  # noqa: E501
            'platform_listing_id': (str, none_type,),  # noqa: E501
            'handling_time_days': (float, none_type,),  # noqa: E501
            'platform_order_id': (str, none_type,),  # noqa: E501
            'buyer_username': (str, none_type,),  # noqa: E501
            'channel_location_id': (str, none_type,),  # noqa: E501
            'package_preset_id': (str, none_type,),  # noqa: E501
            'carrier': (str, none_type,),  # noqa: E501
            'service': (str, none_type,),  # noqa: E501
            'tracking_number': (str, none_type,),  # noqa: E501
            'easypost_shipment_id': (str, none_type,),  # noqa: E501
            'easypost_tracker_id': (str, none_type,),  # noqa: E501
            'easypost_rate_id': (str, none_type,),  # noqa: E501
            'shipping_label_url': (str, none_type,),  # noqa: E501
            'label_purchased_at': (datetime, none_type,),  # noqa: E501
            'shipped_at': (datetime, none_type,),  # noqa: E501
            'estimated_delivery': (str, none_type,),  # noqa: E501
            'delivered_at': (datetime, none_type,),  # noqa: E501
            'carrier_status': (str, none_type,),  # noqa: E501
            'carrier_status_detail': (str, none_type,),  # noqa: E501
            'tracking_history': ([ListOrdersItemTrackingHistory], none_type,),  # noqa: E501
            'delivery_location': (str, none_type,),  # noqa: E501
            'delivery_signature': (str, none_type,),  # noqa: E501
            'tracking_submitted_at': (datetime, none_type,),  # noqa: E501
            'tracking_submit_status': (str, none_type,),  # noqa: E501
            'label_cost': (str, none_type,),  # noqa: E501
            'cost_of_goods': (str, none_type,),  # noqa: E501
            'requested_carrier': (str, none_type,),  # noqa: E501
            'requested_service': (str, none_type,),  # noqa: E501
            'ship_by_at': (datetime, none_type,),  # noqa: E501
            'ship_by_alerted_at': (datetime, none_type,),  # noqa: E501
            'last_status_check_at': (datetime, none_type,),  # noqa: E501
            'last_chat_check_at': (datetime, none_type,),  # noqa: E501
            'dispute_reason': (str, none_type,),  # noqa: E501
            'dispute_platform_case_id': (str, none_type,),  # noqa: E501
            'dispute_resolved_at': (datetime, none_type,),  # noqa: E501
            'refund_amount': (str, none_type,),  # noqa: E501
            'refund_reason': (str, none_type,),  # noqa: E501
            'refund_platform_id': (str, none_type,),  # noqa: E501
            'refunded_at': (datetime, none_type,),  # noqa: E501
            'cancellation_reason': (str, none_type,),  # noqa: E501
            'arrival_condition_requested_at': (datetime, none_type,),  # noqa: E501
            'arrival_condition_submitted_at': (datetime, none_type,),  # noqa: E501
            'arrival_condition_declined_at': (datetime, none_type,),  # noqa: E501
            'delivery_photo_url': (str, none_type,),  # noqa: E501
            'purchase_order_ref': (str, none_type,),  # noqa: E501
            'buyer_email': (str, none_type,),  # noqa: E501
            'deleted_at': (datetime, none_type,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'id': 'id',  # noqa: E501
        'created_at': 'createdAt',  # noqa: E501
        'updated_at': 'updatedAt',  # noqa: E501
        'user_id': 'userId',  # noqa: E501
        'quantity': 'quantity',  # noqa: E501
        'status': 'status',  # noqa: E501
        'platform': 'platform',  # noqa: E501
        'sales_channel': 'salesChannel',  # noqa: E501
        'oversold_by': 'oversoldBy',  # noqa: E501
        'is_disputed': 'isDisputed',  # noqa: E501
        'arrival_condition_photos': 'arrivalConditionPhotos',  # noqa: E501
        'fulfillment_method': 'fulfillmentMethod',  # noqa: E501
        'notes': 'notes',  # noqa: E501
        'cancelled_at': 'cancelledAt',  # noqa: E501
        'listing_id': 'listingId',  # noqa: E501
        'inventory_item_id': 'inventoryItemId',  # noqa: E501
        'platform_listing_id': 'platformListingId',  # noqa: E501
        'handling_time_days': 'handlingTimeDays',  # noqa: E501
        'platform_order_id': 'platformOrderId',  # noqa: E501
        'buyer_username': 'buyerUsername',  # noqa: E501
        'channel_location_id': 'channelLocationId',  # noqa: E501
        'package_preset_id': 'packagePresetId',  # noqa: E501
        'carrier': 'carrier',  # noqa: E501
        'service': 'service',  # noqa: E501
        'tracking_number': 'trackingNumber',  # noqa: E501
        'easypost_shipment_id': 'easypostShipmentId',  # noqa: E501
        'easypost_tracker_id': 'easypostTrackerId',  # noqa: E501
        'easypost_rate_id': 'easypostRateId',  # noqa: E501
        'shipping_label_url': 'shippingLabelUrl',  # noqa: E501
        'label_purchased_at': 'labelPurchasedAt',  # noqa: E501
        'shipped_at': 'shippedAt',  # noqa: E501
        'estimated_delivery': 'estimatedDelivery',  # noqa: E501
        'delivered_at': 'deliveredAt',  # noqa: E501
        'carrier_status': 'carrierStatus',  # noqa: E501
        'carrier_status_detail': 'carrierStatusDetail',  # noqa: E501
        'tracking_history': 'trackingHistory',  # noqa: E501
        'delivery_location': 'deliveryLocation',  # noqa: E501
        'delivery_signature': 'deliverySignature',  # noqa: E501
        'tracking_submitted_at': 'trackingSubmittedAt',  # noqa: E501
        'tracking_submit_status': 'trackingSubmitStatus',  # noqa: E501
        'label_cost': 'labelCost',  # noqa: E501
        'cost_of_goods': 'costOfGoods',  # noqa: E501
        'requested_carrier': 'requestedCarrier',  # noqa: E501
        'requested_service': 'requestedService',  # noqa: E501
        'ship_by_at': 'shipByAt',  # noqa: E501
        'ship_by_alerted_at': 'shipByAlertedAt',  # noqa: E501
        'last_status_check_at': 'lastStatusCheckAt',  # noqa: E501
        'last_chat_check_at': 'lastChatCheckAt',  # noqa: E501
        'dispute_reason': 'disputeReason',  # noqa: E501
        'dispute_platform_case_id': 'disputePlatformCaseId',  # noqa: E501
        'dispute_resolved_at': 'disputeResolvedAt',  # noqa: E501
        'refund_amount': 'refundAmount',  # noqa: E501
        'refund_reason': 'refundReason',  # noqa: E501
        'refund_platform_id': 'refundPlatformId',  # noqa: E501
        'refunded_at': 'refundedAt',  # noqa: E501
        'cancellation_reason': 'cancellationReason',  # noqa: E501
        'arrival_condition_requested_at': 'arrivalConditionRequestedAt',  # noqa: E501
        'arrival_condition_submitted_at': 'arrivalConditionSubmittedAt',  # noqa: E501
        'arrival_condition_declined_at': 'arrivalConditionDeclinedAt',  # noqa: E501
        'delivery_photo_url': 'deliveryPhotoUrl',  # noqa: E501
        'purchase_order_ref': 'purchaseOrderRef',  # noqa: E501
        'buyer_email': 'buyerEmail',  # noqa: E501
        'deleted_at': 'deletedAt',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, id, created_at, updated_at, user_id, quantity, status, platform, sales_channel, oversold_by, is_disputed, arrival_condition_photos, fulfillment_method, *args, **kwargs):  # noqa: E501
        """GetOrderResponse - a model defined in OpenAPI

        Args:
            id (str):
            created_at (datetime):
            updated_at (datetime):
            user_id (str):
            quantity (float):
            status (str):
            platform (str):
            sales_channel (str):
            oversold_by (float):
            is_disputed (bool):
            arrival_condition_photos ([str]):
            fulfillment_method (str):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            notes (str, none_type): [optional]  # noqa: E501
            cancelled_at (datetime, none_type): [optional]  # noqa: E501
            listing_id (str, none_type): [optional]  # noqa: E501
            inventory_item_id (str, none_type): [optional]  # noqa: E501
            platform_listing_id (str, none_type): [optional]  # noqa: E501
            handling_time_days (float, none_type): [optional]  # noqa: E501
            platform_order_id (str, none_type): [optional]  # noqa: E501
            buyer_username (str, none_type): [optional]  # noqa: E501
            channel_location_id (str, none_type): [optional]  # noqa: E501
            package_preset_id (str, none_type): [optional]  # noqa: E501
            carrier (str, none_type): [optional]  # noqa: E501
            service (str, none_type): [optional]  # noqa: E501
            tracking_number (str, none_type): [optional]  # noqa: E501
            easypost_shipment_id (str, none_type): [optional]  # noqa: E501
            easypost_tracker_id (str, none_type): [optional]  # noqa: E501
            easypost_rate_id (str, none_type): [optional]  # noqa: E501
            shipping_label_url (str, none_type): [optional]  # noqa: E501
            label_purchased_at (datetime, none_type): [optional]  # noqa: E501
            shipped_at (datetime, none_type): [optional]  # noqa: E501
            estimated_delivery (str, none_type): [optional]  # noqa: E501
            delivered_at (datetime, none_type): [optional]  # noqa: E501
            carrier_status (str, none_type): [optional]  # noqa: E501
            carrier_status_detail (str, none_type): [optional]  # noqa: E501
            tracking_history ([ListOrdersItemTrackingHistory], none_type): [optional]  # noqa: E501
            delivery_location (str, none_type): [optional]  # noqa: E501
            delivery_signature (str, none_type): [optional]  # noqa: E501
            tracking_submitted_at (datetime, none_type): [optional]  # noqa: E501
            tracking_submit_status (str, none_type): [optional]  # noqa: E501
            label_cost (str, none_type): [optional]  # noqa: E501
            cost_of_goods (str, none_type): [optional]  # noqa: E501
            requested_carrier (str, none_type): [optional]  # noqa: E501
            requested_service (str, none_type): [optional]  # noqa: E501
            ship_by_at (datetime, none_type): [optional]  # noqa: E501
            ship_by_alerted_at (datetime, none_type): [optional]  # noqa: E501
            last_status_check_at (datetime, none_type): [optional]  # noqa: E501
            last_chat_check_at (datetime, none_type): [optional]  # noqa: E501
            dispute_reason (str, none_type): [optional]  # noqa: E501
            dispute_platform_case_id (str, none_type): [optional]  # noqa: E501
            dispute_resolved_at (datetime, none_type): [optional]  # noqa: E501
            refund_amount (str, none_type): [optional]  # noqa: E501
            refund_reason (str, none_type): [optional]  # noqa: E501
            refund_platform_id (str, none_type): [optional]  # noqa: E501
            refunded_at (datetime, none_type): [optional]  # noqa: E501
            cancellation_reason (str, none_type): [optional]  # noqa: E501
            arrival_condition_requested_at (datetime, none_type): [optional]  # noqa: E501
            arrival_condition_submitted_at (datetime, none_type): [optional]  # noqa: E501
            arrival_condition_declined_at (datetime, none_type): [optional]  # noqa: E501
            delivery_photo_url (str, none_type): [optional]  # noqa: E501
            purchase_order_ref (str, none_type): [optional]  # noqa: E501
            buyer_email (str, none_type): [optional]  # noqa: E501
            deleted_at (datetime, none_type): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.id = id
        self.created_at = created_at
        self.updated_at = updated_at
        self.user_id = user_id
        self.quantity = quantity
        self.status = status
        self.platform = platform
        self.sales_channel = sales_channel
        self.oversold_by = oversold_by
        self.is_disputed = is_disputed
        self.arrival_condition_photos = arrival_condition_photos
        self.fulfillment_method = fulfillment_method
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, id, created_at, updated_at, user_id, quantity, status, platform, sales_channel, oversold_by, is_disputed, arrival_condition_photos, fulfillment_method, *args, **kwargs):  # noqa: E501
        """GetOrderResponse - a model defined in OpenAPI

        Args:
            id (str):
            created_at (datetime):
            updated_at (datetime):
            user_id (str):
            quantity (float):
            status (str):
            platform (str):
            sales_channel (str):
            oversold_by (float):
            is_disputed (bool):
            arrival_condition_photos ([str]):
            fulfillment_method (str):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            notes (str, none_type): [optional]  # noqa: E501
            cancelled_at (datetime, none_type): [optional]  # noqa: E501
            listing_id (str, none_type): [optional]  # noqa: E501
            inventory_item_id (str, none_type): [optional]  # noqa: E501
            platform_listing_id (str, none_type): [optional]  # noqa: E501
            handling_time_days (float, none_type): [optional]  # noqa: E501
            platform_order_id (str, none_type): [optional]  # noqa: E501
            buyer_username (str, none_type): [optional]  # noqa: E501
            channel_location_id (str, none_type): [optional]  # noqa: E501
            package_preset_id (str, none_type): [optional]  # noqa: E501
            carrier (str, none_type): [optional]  # noqa: E501
            service (str, none_type): [optional]  # noqa: E501
            tracking_number (str, none_type): [optional]  # noqa: E501
            easypost_shipment_id (str, none_type): [optional]  # noqa: E501
            easypost_tracker_id (str, none_type): [optional]  # noqa: E501
            easypost_rate_id (str, none_type): [optional]  # noqa: E501
            shipping_label_url (str, none_type): [optional]  # noqa: E501
            label_purchased_at (datetime, none_type): [optional]  # noqa: E501
            shipped_at (datetime, none_type): [optional]  # noqa: E501
            estimated_delivery (str, none_type): [optional]  # noqa: E501
            delivered_at (datetime, none_type): [optional]  # noqa: E501
            carrier_status (str, none_type): [optional]  # noqa: E501
            carrier_status_detail (str, none_type): [optional]  # noqa: E501
            tracking_history ([ListOrdersItemTrackingHistory], none_type): [optional]  # noqa: E501
            delivery_location (str, none_type): [optional]  # noqa: E501
            delivery_signature (str, none_type): [optional]  # noqa: E501
            tracking_submitted_at (datetime, none_type): [optional]  # noqa: E501
            tracking_submit_status (str, none_type): [optional]  # noqa: E501
            label_cost (str, none_type): [optional]  # noqa: E501
            cost_of_goods (str, none_type): [optional]  # noqa: E501
            requested_carrier (str, none_type): [optional]  # noqa: E501
            requested_service (str, none_type): [optional]  # noqa: E501
            ship_by_at (datetime, none_type): [optional]  # noqa: E501
            ship_by_alerted_at (datetime, none_type): [optional]  # noqa: E501
            last_status_check_at (datetime, none_type): [optional]  # noqa: E501
            last_chat_check_at (datetime, none_type): [optional]  # noqa: E501
            dispute_reason (str, none_type): [optional]  # noqa: E501
            dispute_platform_case_id (str, none_type): [optional]  # noqa: E501
            dispute_resolved_at (datetime, none_type): [optional]  # noqa: E501
            refund_amount (str, none_type): [optional]  # noqa: E501
            refund_reason (str, none_type): [optional]  # noqa: E501
            refund_platform_id (str, none_type): [optional]  # noqa: E501
            refunded_at (datetime, none_type): [optional]  # noqa: E501
            cancellation_reason (str, none_type): [optional]  # noqa: E501
            arrival_condition_requested_at (datetime, none_type): [optional]  # noqa: E501
            arrival_condition_submitted_at (datetime, none_type): [optional]  # noqa: E501
            arrival_condition_declined_at (datetime, none_type): [optional]  # noqa: E501
            delivery_photo_url (str, none_type): [optional]  # noqa: E501
            purchase_order_ref (str, none_type): [optional]  # noqa: E501
            buyer_email (str, none_type): [optional]  # noqa: E501
            deleted_at (datetime, none_type): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.id = id
        self.created_at = created_at
        self.updated_at = updated_at
        self.user_id = user_id
        self.quantity = quantity
        self.status = status
        self.platform = platform
        self.sales_channel = sales_channel
        self.oversold_by = oversold_by
        self.is_disputed = is_disputed
        self.arrival_condition_photos = arrival_condition_photos
        self.fulfillment_method = fulfillment_method
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
