"""
    Crossly Buyer API

    The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from crossly_buyer.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from crossly_buyer.exceptions import ApiAttributeError



class GetCategoryResponseMain(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        return {
            '_0': (str,),  # noqa: E501
            '_1': (str,),  # noqa: E501
            '_2': (str,),  # noqa: E501
            '_3': (str,),  # noqa: E501
            '_4': (str,),  # noqa: E501
            '_5': (str,),  # noqa: E501
            '_6': (str,),  # noqa: E501
            '_7': (str,),  # noqa: E501
            '_8': (str,),  # noqa: E501
            '_9': (str,),  # noqa: E501
            '_10': (str,),  # noqa: E501
            '_11': (str,),  # noqa: E501
            '_12': (str,),  # noqa: E501
            '_13': (str,),  # noqa: E501
            '_14': (str,),  # noqa: E501
            '_15': (str,),  # noqa: E501
            '_16': (str,),  # noqa: E501
            '_17': (str,),  # noqa: E501
            '_18': (str,),  # noqa: E501
            '_19': (str,),  # noqa: E501
            '_20': (str,),  # noqa: E501
            '_21': (str,),  # noqa: E501
            '_22': (str,),  # noqa: E501
            '_23': (str,),  # noqa: E501
            '_24': (str,),  # noqa: E501
            '_25': (str,),  # noqa: E501
            '_26': (str,),  # noqa: E501
            '_27': (str,),  # noqa: E501
            '_28': (str,),  # noqa: E501
            '_29': (str,),  # noqa: E501
            '_30': (str,),  # noqa: E501
            '_31': (str,),  # noqa: E501
            'length': (float,),  # noqa: E501
            'to_string': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},),  # noqa: E501
            'to_locale_string': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},),  # noqa: E501
            'concat': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},),  # noqa: E501
            'join': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},),  # noqa: E501
            'slice': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},),  # noqa: E501
            'index_of': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},),  # noqa: E501
            'last_index_of': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},),  # noqa: E501
            'every': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},),  # noqa: E501
            'some': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},),  # noqa: E501
            'for_each': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},),  # noqa: E501
            'map': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},),  # noqa: E501
            'filter': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},),  # noqa: E501
            'reduce': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},),  # noqa: E501
            'reduce_right': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},),  # noqa: E501
            'find': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},),  # noqa: E501
            'find_index': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},),  # noqa: E501
            'entries': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},),  # noqa: E501
            'keys': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},),  # noqa: E501
            'values': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},),  # noqa: E501
            'includes': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},),  # noqa: E501
            'flat_map': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},),  # noqa: E501
            'flat': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},),  # noqa: E501
            'at': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},),  # noqa: E501
            'iterator446': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},),  # noqa: E501
            'unscopables448': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        '_0': '0',  # noqa: E501
        '_1': '1',  # noqa: E501
        '_2': '2',  # noqa: E501
        '_3': '3',  # noqa: E501
        '_4': '4',  # noqa: E501
        '_5': '5',  # noqa: E501
        '_6': '6',  # noqa: E501
        '_7': '7',  # noqa: E501
        '_8': '8',  # noqa: E501
        '_9': '9',  # noqa: E501
        '_10': '10',  # noqa: E501
        '_11': '11',  # noqa: E501
        '_12': '12',  # noqa: E501
        '_13': '13',  # noqa: E501
        '_14': '14',  # noqa: E501
        '_15': '15',  # noqa: E501
        '_16': '16',  # noqa: E501
        '_17': '17',  # noqa: E501
        '_18': '18',  # noqa: E501
        '_19': '19',  # noqa: E501
        '_20': '20',  # noqa: E501
        '_21': '21',  # noqa: E501
        '_22': '22',  # noqa: E501
        '_23': '23',  # noqa: E501
        '_24': '24',  # noqa: E501
        '_25': '25',  # noqa: E501
        '_26': '26',  # noqa: E501
        '_27': '27',  # noqa: E501
        '_28': '28',  # noqa: E501
        '_29': '29',  # noqa: E501
        '_30': '30',  # noqa: E501
        '_31': '31',  # noqa: E501
        'length': 'length',  # noqa: E501
        'to_string': 'toString',  # noqa: E501
        'to_locale_string': 'toLocaleString',  # noqa: E501
        'concat': 'concat',  # noqa: E501
        'join': 'join',  # noqa: E501
        'slice': 'slice',  # noqa: E501
        'index_of': 'indexOf',  # noqa: E501
        'last_index_of': 'lastIndexOf',  # noqa: E501
        'every': 'every',  # noqa: E501
        'some': 'some',  # noqa: E501
        'for_each': 'forEach',  # noqa: E501
        'map': 'map',  # noqa: E501
        'filter': 'filter',  # noqa: E501
        'reduce': 'reduce',  # noqa: E501
        'reduce_right': 'reduceRight',  # noqa: E501
        'find': 'find',  # noqa: E501
        'find_index': 'findIndex',  # noqa: E501
        'entries': 'entries',  # noqa: E501
        'keys': 'keys',  # noqa: E501
        'values': 'values',  # noqa: E501
        'includes': 'includes',  # noqa: E501
        'flat_map': 'flatMap',  # noqa: E501
        'flat': 'flat',  # noqa: E501
        'at': 'at',  # noqa: E501
        'iterator446': '__@iterator@446',  # noqa: E501
        'unscopables448': '__@unscopables@448',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, _0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, length, to_string, to_locale_string, concat, join, slice, index_of, last_index_of, every, some, for_each, map, filter, reduce, reduce_right, find, find_index, entries, keys, values, includes, flat_map, flat, at, iterator446, unscopables448, *args, **kwargs):  # noqa: E501
        """GetCategoryResponseMain - a model defined in OpenAPI

        Args:
            _0 (str):
            _1 (str):
            _2 (str):
            _3 (str):
            _4 (str):
            _5 (str):
            _6 (str):
            _7 (str):
            _8 (str):
            _9 (str):
            _10 (str):
            _11 (str):
            _12 (str):
            _13 (str):
            _14 (str):
            _15 (str):
            _16 (str):
            _17 (str):
            _18 (str):
            _19 (str):
            _20 (str):
            _21 (str):
            _22 (str):
            _23 (str):
            _24 (str):
            _25 (str):
            _26 (str):
            _27 (str):
            _28 (str):
            _29 (str):
            _30 (str):
            _31 (str):
            length (float):
            to_string ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Returns a string representation of an array.
            to_locale_string ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Returns a string representation of an array. The elements are converted to string using their toLocaleString methods.
            concat ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Combines two or more arrays.
            join ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Adds all the elements of an array separated by the specified separator string.
            slice ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Returns a section of an array.
            index_of ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Returns the index of the first occurrence of a value in an array.
            last_index_of ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Returns the index of the last occurrence of a specified value in an array.
            every ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Determines whether all the members of an array satisfy the specified test.
            some ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Determines whether the specified callback function returns true for any element of an array.
            for_each ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Performs the specified action for each element in an array.
            map ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Calls a defined callback function on each element of an array, and returns an array that contains the results.
            filter ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Returns the elements of an array that meet the condition specified in a callback function.
            reduce ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Calls the specified callback function for all the elements in an array. The return value of the callback function is the accumulated result, and is provided as an argument in the next call to the callback function.
            reduce_right ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Calls the specified callback function for all the elements in an array, in descending order. The return value of the callback function is the accumulated result, and is provided as an argument in the next call to the callback function.
            find ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Returns the value of the first element in the array where predicate is true, and undefined otherwise.
            find_index ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Returns the index of the first element in the array where predicate is true, and -1 otherwise.
            entries ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Returns an iterable of key, value pairs for every entry in the array
            keys ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Returns an iterable of keys in the array
            values ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Returns an iterable of values in the array
            includes ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Determines whether an array includes a certain element, returning true or false as appropriate.
            flat_map ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Calls a defined callback function on each element of an array. Then, flattens the result into a new array. This is identical to a map followed by flat with depth 1.
            flat ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Returns a new array with all sub-array elements concatenated into it recursively up to the specified depth.
            at ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Returns the item located at the specified index.
            iterator446 ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Iterator of values in the array.
            unscopables448 ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Is an object whose properties have the value 'true' when they will be absent when used in a 'with' statement.

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self._0 = _0
        self._1 = _1
        self._2 = _2
        self._3 = _3
        self._4 = _4
        self._5 = _5
        self._6 = _6
        self._7 = _7
        self._8 = _8
        self._9 = _9
        self._10 = _10
        self._11 = _11
        self._12 = _12
        self._13 = _13
        self._14 = _14
        self._15 = _15
        self._16 = _16
        self._17 = _17
        self._18 = _18
        self._19 = _19
        self._20 = _20
        self._21 = _21
        self._22 = _22
        self._23 = _23
        self._24 = _24
        self._25 = _25
        self._26 = _26
        self._27 = _27
        self._28 = _28
        self._29 = _29
        self._30 = _30
        self._31 = _31
        self.length = length
        self.to_string = to_string
        self.to_locale_string = to_locale_string
        self.concat = concat
        self.join = join
        self.slice = slice
        self.index_of = index_of
        self.last_index_of = last_index_of
        self.every = every
        self.some = some
        self.for_each = for_each
        self.map = map
        self.filter = filter
        self.reduce = reduce
        self.reduce_right = reduce_right
        self.find = find
        self.find_index = find_index
        self.entries = entries
        self.keys = keys
        self.values = values
        self.includes = includes
        self.flat_map = flat_map
        self.flat = flat
        self.at = at
        self.iterator446 = iterator446
        self.unscopables448 = unscopables448
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, _0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, length, to_string, to_locale_string, concat, join, slice, index_of, last_index_of, every, some, for_each, map, filter, reduce, reduce_right, find, find_index, entries, keys, values, includes, flat_map, flat, at, iterator446, unscopables448, *args, **kwargs):  # noqa: E501
        """GetCategoryResponseMain - a model defined in OpenAPI

        Args:
            _0 (str):
            _1 (str):
            _2 (str):
            _3 (str):
            _4 (str):
            _5 (str):
            _6 (str):
            _7 (str):
            _8 (str):
            _9 (str):
            _10 (str):
            _11 (str):
            _12 (str):
            _13 (str):
            _14 (str):
            _15 (str):
            _16 (str):
            _17 (str):
            _18 (str):
            _19 (str):
            _20 (str):
            _21 (str):
            _22 (str):
            _23 (str):
            _24 (str):
            _25 (str):
            _26 (str):
            _27 (str):
            _28 (str):
            _29 (str):
            _30 (str):
            _31 (str):
            length (float):
            to_string ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Returns a string representation of an array.
            to_locale_string ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Returns a string representation of an array. The elements are converted to string using their toLocaleString methods.
            concat ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Combines two or more arrays.
            join ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Adds all the elements of an array separated by the specified separator string.
            slice ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Returns a section of an array.
            index_of ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Returns the index of the first occurrence of a value in an array.
            last_index_of ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Returns the index of the last occurrence of a specified value in an array.
            every ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Determines whether all the members of an array satisfy the specified test.
            some ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Determines whether the specified callback function returns true for any element of an array.
            for_each ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Performs the specified action for each element in an array.
            map ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Calls a defined callback function on each element of an array, and returns an array that contains the results.
            filter ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Returns the elements of an array that meet the condition specified in a callback function.
            reduce ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Calls the specified callback function for all the elements in an array. The return value of the callback function is the accumulated result, and is provided as an argument in the next call to the callback function.
            reduce_right ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Calls the specified callback function for all the elements in an array, in descending order. The return value of the callback function is the accumulated result, and is provided as an argument in the next call to the callback function.
            find ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Returns the value of the first element in the array where predicate is true, and undefined otherwise.
            find_index ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Returns the index of the first element in the array where predicate is true, and -1 otherwise.
            entries ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Returns an iterable of key, value pairs for every entry in the array
            keys ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Returns an iterable of keys in the array
            values ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Returns an iterable of values in the array
            includes ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Determines whether an array includes a certain element, returning true or false as appropriate.
            flat_map ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Calls a defined callback function on each element of an array. Then, flattens the result into a new array. This is identical to a map followed by flat with depth 1.
            flat ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Returns a new array with all sub-array elements concatenated into it recursively up to the specified depth.
            at ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Returns the item located at the specified index.
            iterator446 ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Iterator of values in the array.
            unscopables448 ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): Is an object whose properties have the value 'true' when they will be absent when used in a 'with' statement.

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self._0 = _0
        self._1 = _1
        self._2 = _2
        self._3 = _3
        self._4 = _4
        self._5 = _5
        self._6 = _6
        self._7 = _7
        self._8 = _8
        self._9 = _9
        self._10 = _10
        self._11 = _11
        self._12 = _12
        self._13 = _13
        self._14 = _14
        self._15 = _15
        self._16 = _16
        self._17 = _17
        self._18 = _18
        self._19 = _19
        self._20 = _20
        self._21 = _21
        self._22 = _22
        self._23 = _23
        self._24 = _24
        self._25 = _25
        self._26 = _26
        self._27 = _27
        self._28 = _28
        self._29 = _29
        self._30 = _30
        self._31 = _31
        self.length = length
        self.to_string = to_string
        self.to_locale_string = to_locale_string
        self.concat = concat
        self.join = join
        self.slice = slice
        self.index_of = index_of
        self.last_index_of = last_index_of
        self.every = every
        self.some = some
        self.for_each = for_each
        self.map = map
        self.filter = filter
        self.reduce = reduce
        self.reduce_right = reduce_right
        self.find = find
        self.find_index = find_index
        self.entries = entries
        self.keys = keys
        self.values = values
        self.includes = includes
        self.flat_map = flat_map
        self.flat = flat
        self.at = at
        self.iterator446 = iterator446
        self.unscopables448 = unscopables448
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
