"""
    Crossly Buyer API

    The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import crossly_buyer
from crossly_buyer.model.list_variation_groups_item_members import ListVariationGroupsItemMembers
from crossly_buyer.model.list_variation_groups_item_rollup import ListVariationGroupsItemRollup
globals()['ListVariationGroupsItemMembers'] = ListVariationGroupsItemMembers
globals()['ListVariationGroupsItemRollup'] = ListVariationGroupsItemRollup
from crossly_buyer.model.get_variation_group_response import GetVariationGroupResponse


class TestGetVariationGroupResponse(unittest.TestCase):
    """GetVariationGroupResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetVariationGroupResponse(self):
        """Test GetVariationGroupResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetVariationGroupResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
