"""
    Crossly Buyer API

    The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import crossly_buyer
from crossly_buyer.model.get_spatial_public_response_profile import GetSpatialPublicResponseProfile
from crossly_buyer.model.get_spatial_public_response_solved import GetSpatialPublicResponseSolved
from crossly_buyer.model.get_spatial_scene_response_breakdowns import GetSpatialSceneResponseBreakdowns
from crossly_buyer.model.get_spatial_scene_response_items import GetSpatialSceneResponseItems
from crossly_buyer.model.get_spatial_scene_response_scene import GetSpatialSceneResponseScene
from crossly_buyer.model.get_spatial_scene_response_stats import GetSpatialSceneResponseStats
globals()['GetSpatialPublicResponseProfile'] = GetSpatialPublicResponseProfile
globals()['GetSpatialPublicResponseSolved'] = GetSpatialPublicResponseSolved
globals()['GetSpatialSceneResponseBreakdowns'] = GetSpatialSceneResponseBreakdowns
globals()['GetSpatialSceneResponseItems'] = GetSpatialSceneResponseItems
globals()['GetSpatialSceneResponseScene'] = GetSpatialSceneResponseScene
globals()['GetSpatialSceneResponseStats'] = GetSpatialSceneResponseStats
from crossly_buyer.model.get_spatial_scene_response import GetSpatialSceneResponse


class TestGetSpatialSceneResponse(unittest.TestCase):
    """GetSpatialSceneResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetSpatialSceneResponse(self):
        """Test GetSpatialSceneResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetSpatialSceneResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
