"""
    Crossly Buyer API

    The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import crossly_buyer
from crossly_buyer.model.list_cbx_wallet_payment_review_item import ListCbxWalletPaymentReviewItem


class TestListCbxWalletPaymentReviewItem(unittest.TestCase):
    """ListCbxWalletPaymentReviewItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListCbxWalletPaymentReviewItem(self):
        """Test ListCbxWalletPaymentReviewItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListCbxWalletPaymentReviewItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
