"""
    Crossly Buyer API

    The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import crossly_buyer
from crossly_buyer.model.get_analytic_bookkeeping_response_annual_totals import GetAnalyticBookkeepingResponseAnnualTotals
from crossly_buyer.model.get_analytic_bookkeeping_response_monthly_pl import GetAnalyticBookkeepingResponseMonthlyPL
from crossly_buyer.model.get_analytic_bookkeeping_response_platform_breakdown import GetAnalyticBookkeepingResponsePlatformBreakdown
globals()['GetAnalyticBookkeepingResponseAnnualTotals'] = GetAnalyticBookkeepingResponseAnnualTotals
globals()['GetAnalyticBookkeepingResponseMonthlyPL'] = GetAnalyticBookkeepingResponseMonthlyPL
globals()['GetAnalyticBookkeepingResponsePlatformBreakdown'] = GetAnalyticBookkeepingResponsePlatformBreakdown
from crossly_buyer.model.get_analytic_bookkeeping_response import GetAnalyticBookkeepingResponse


class TestGetAnalyticBookkeepingResponse(unittest.TestCase):
    """GetAnalyticBookkeepingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetAnalyticBookkeepingResponse(self):
        """Test GetAnalyticBookkeepingResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetAnalyticBookkeepingResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
