"""
    Crossly Buyer API

    The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import crossly_buyer
from crossly_buyer.model.get_spatial_public_response_solved_dividers import GetSpatialPublicResponseSolvedDividers


class TestGetSpatialPublicResponseSolvedDividers(unittest.TestCase):
    """GetSpatialPublicResponseSolvedDividers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetSpatialPublicResponseSolvedDividers(self):
        """Test GetSpatialPublicResponseSolvedDividers"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetSpatialPublicResponseSolvedDividers()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
