"""
    Crossly Buyer API

    The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import crossly_buyer
from crossly_buyer.model.pagination import Pagination
globals()['Pagination'] = Pagination
from crossly_buyer.model.v1_list import V1List


class TestV1List(unittest.TestCase):
    """V1List unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1List(self):
        """Test V1List"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1List()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
