"""
    Crossly Seller API

    The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import crossly
from crossly.api.network_api import NetworkApi  # noqa: E501


class TestNetworkApi(unittest.TestCase):
    """NetworkApi unit test stubs"""

    def setUp(self):
        self.api = NetworkApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_network_pool(self):
        """Test case for create_network_pool

        Join the Crossly Network reciprocal engagement pool.  # noqa: E501
        """
        pass

    def test_delete_network_pool(self):
        """Test case for delete_network_pool

        Leave the Crossly Network pool.  # noqa: E501
        """
        pass

    def test_get_network_pool(self):
        """Test case for get_network_pool

        The seller's Crossly Network pool membership row.  # noqa: E501
        """
        pass

    def test_get_network_pool_size(self):
        """Test case for get_network_pool_size

        Total members in the Crossly Network pool.  # noqa: E501
        """
        pass

    def test_list_network_pool_log(self):
        """Test case for list_network_pool_log

        Recent engagement history — both sent and received.  # noqa: E501
        """
        pass

    def test_update_network_pool(self):
        """Test case for update_network_pool

        Update per-action toggles + platforms on pool membership.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
