"""
    Crossly Seller API

    The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import crossly
from crossly.api.account_api import AccountApi  # noqa: E501


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self):
        self.api = AccountApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_account_cancel_deletion(self):
        """Test case for create_account_cancel_deletion

        Cancel a pending account deletion.  # noqa: E501
        """
        pass

    def test_create_account_logout_all(self):
        """Test case for create_account_logout_all

        Revoke every browser auth session for this user.  # noqa: E501
        """
        pass

    def test_create_account_request_deletion(self):
        """Test case for create_account_request_deletion

        Schedule account deletion after a grace period.  # noqa: E501
        """
        pass

    def test_delete_auth_session(self):
        """Test case for delete_auth_session

        Revoke all active browser sessions.  # noqa: E501
        """
        pass

    def test_delete_auth_session_by_session_id(self):
        """Test case for delete_auth_session_by_session_id

        Revoke a single browser session by id.  # noqa: E501
        """
        pass

    def test_delete_connected_app(self):
        """Test case for delete_connected_app

        Disconnect a third-party app. Its tokens stop working immediately.  # noqa: E501
        """
        pass

    def test_get_account_deletion_status(self):
        """Test case for get_account_deletion_status

        Get the currently-pending deletion request, if any.  # noqa: E501
        """
        pass

    def test_get_me(self):
        """Test case for get_me

        Identity check — authenticated user + PAT scopes + account state.  # noqa: E501
        """
        pass

    def test_list_auth_sessions(self):
        """Test case for list_auth_sessions

        List active browser auth sessions.  # noqa: E501
        """
        pass

    def test_list_connected_apps(self):
        """Test case for list_connected_apps

        List third-party OAuth apps with access to this account.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
