"""
    Crossly Seller API

    The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import crossly
from crossly.api.cbx_api import CBXApi  # noqa: E501


class TestCBXApi(unittest.TestCase):
    """CBXApi unit test stubs"""

    def setUp(self):
        self.api = CBXApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_cbx_accrual(self):
        """Test case for create_cbx_accrual

        Record cashback a user earned, in cents.  # noqa: E501
        """
        pass

    def test_create_cbx_accrual_purchase(self):
        """Test case for create_cbx_accrual_purchase

        Accrue cashback for an order at the resolved rate.  # noqa: E501
        """
        pass

    def test_create_cbx_accrual_reverse(self):
        """Test case for create_cbx_accrual_reverse

        Claw back a pending accrual — a refund, a cancellation, fraud.  # noqa: E501
        """
        pass

    def test_create_cbx_ad_credit_purchase(self):
        """Test case for create_cbx_ad_credit_purchase

        Claim ad credit against a CBX transfer you sent.  # noqa: E501
        """
        pass

    def test_create_cbx_ad_credit_quote(self):
        """Test case for create_cbx_ad_credit_quote

        What a given number of tokens buys in ad credit.  # noqa: E501
        """
        pass

    def test_create_cbx_ad_credit_spend(self):
        """Test case for create_cbx_ad_credit_spend

        Consume credit for a billing period.  # noqa: E501
        """
        pass

    def test_create_cbx_boost(self):
        """Test case for create_cbx_boost

        Fund elevated cashback on matching items.  # noqa: E501
        """
        pass

    def test_create_cbx_boost_pause(self):
        """Test case for create_cbx_boost_pause

        Stop a boost from matching further orders.  # noqa: E501
        """
        pass

    def test_create_cbx_campaign(self):
        """Test case for create_cbx_campaign

        Create a campaign in draft.  # noqa: E501
        """
        pass

    def test_create_cbx_campaign_approve(self):
        """Test case for create_cbx_campaign_approve

        Approve the previewed recipient list.  # noqa: E501
        """
        pass

    def test_create_cbx_campaign_execute(self):
        """Test case for create_cbx_campaign_execute

        Pay an approved campaign.  # noqa: E501
        """
        pass

    def test_create_cbx_campaign_preview(self):
        """Test case for create_cbx_campaign_preview

        Compute the recipient list without paying it.  # noqa: E501
        """
        pass

    def test_create_cbx_claim(self):
        """Test case for create_cbx_claim

        Reserve a claim. Debits the balance and queues the transfer.  # noqa: E501
        """
        pass

    def test_create_cbx_claim_quote(self):
        """Test case for create_cbx_claim_quote

        What a claim would cost, without committing to it.  # noqa: E501
        """
        pass

    def test_create_cbx_claim_send(self):
        """Test case for create_cbx_claim_send

        Send a reserved claim on chain.  # noqa: E501
        """
        pass

    def test_create_cbx_credit_draw(self):
        """Test case for create_cbx_credit_draw

        Draw against a line, receiving grant credit.  # noqa: E501
        """
        pass

    def test_create_cbx_credit_freeze(self):
        """Test case for create_cbx_credit_freeze

        Stop new draws. Leaves the drawn balance on its terms.  # noqa: E501
        """
        pass

    def test_create_cbx_credit_refresh(self):
        """Test case for create_cbx_credit_refresh

        Recompute a limit from trading history and stake.  # noqa: E501
        """
        pass

    def test_create_cbx_credit_repay(self):
        """Test case for create_cbx_credit_repay

        Apply a repayment to a line.  # noqa: E501
        """
        pass

    def test_create_cbx_disbursement_rule(self):
        """Test case for create_cbx_disbursement_rule

        Fire a distribution when the events pool crosses a threshold.  # noqa: E501
        """
        pass

    def test_create_cbx_disbursement_rule_active(self):
        """Test case for create_cbx_disbursement_rule_active

        Enable or disable a rule.  # noqa: E501
        """
        pass

    def test_create_cbx_disbursement_rule_check(self):
        """Test case for create_cbx_disbursement_rule_check

        Evaluate a rule now. Fires it if every gate passes.  # noqa: E501
        """
        pass

    def test_create_cbx_earn_tier(self):
        """Test case for create_cbx_earn_tier

        Define an earn term.  # noqa: E501
        """
        pass

    def test_create_cbx_rate_quote(self):
        """Test case for create_cbx_rate_quote

        What would this order earn, and why.  # noqa: E501
        """
        pass

    def test_create_cbx_redemption(self):
        """Test case for create_cbx_redemption

        Pay for a service in CBX.  # noqa: E501
        """
        pass

    def test_create_cbx_redemption_quote(self):
        """Test case for create_cbx_redemption_quote

        What a service costs in tokens right now.  # noqa: E501
        """
        pass

    def test_create_cbx_revenue_sweep(self):
        """Test case for create_cbx_revenue_sweep

        Move accrued revenue from the reserve to your revenue wallet.  # noqa: E501
        """
        pass

    def test_create_cbx_spend(self):
        """Test case for create_cbx_spend

        Redeem a user's CBX against an order.  # noqa: E501
        """
        pass

    def test_create_cbx_spend_reverse(self):
        """Test case for create_cbx_spend_reverse

        Refund a spend — give the tokens back and claw the skim back.  # noqa: E501
        """
        pass

    def test_create_cbx_stake_tier(self):
        """Test case for create_cbx_stake_tier

        Define a staking tier.  # noqa: E501
        """
        pass

    def test_create_cbx_subject(self):
        """Test case for create_cbx_subject

        Map one of your user ids to a CBX subject.  # noqa: E501
        """
        pass

    def test_create_cbx_subject_grant(self):
        """Test case for create_cbx_subject_grant

        Issue grant credit — in-platform, non-withdrawable.  # noqa: E501
        """
        pass

    def test_create_cbx_subject_spend_plan(self):
        """Test case for create_cbx_subject_spend_plan

        Which balances would pay for a spend, and in what order.  # noqa: E501
        """
        pass

    def test_create_cbx_subject_stake(self):
        """Test case for create_cbx_subject_stake

        Lock a subject's tokens for a tier.  # noqa: E501
        """
        pass

    def test_create_cbx_subject_stake_unstake(self):
        """Test case for create_cbx_subject_stake_unstake

        Start the cooldown. Tokens unlock when it elapses.  # noqa: E501
        """
        pass

    def test_create_cbx_wallet_challenge(self):
        """Test case for create_cbx_wallet_challenge

        Start wallet verification. Returns a message for the user to sign.  # noqa: E501
        """
        pass

    def test_create_cbx_wallet_payment_confirm(self):
        """Test case for create_cbx_wallet_payment_confirm

        Present the signature. Returns a ship / do-not-ship decision.  # noqa: E501
        """
        pass

    def test_create_cbx_wallet_payment_quote(self):
        """Test case for create_cbx_wallet_payment_quote

        Build a transfer for the buyer to sign themselves.  # noqa: E501
        """
        pass

    def test_create_cbx_wallet_payment_resolve(self):
        """Test case for create_cbx_wallet_payment_resolve

        A human decides on a held payment.  # noqa: E501
        """
        pass

    def test_create_cbx_wallet_verify(self):
        """Test case for create_cbx_wallet_verify

        Complete wallet verification with the user's signature.  # noqa: E501
        """
        pass

    def test_get_cbx_ad_credit(self):
        """Test case for get_cbx_ad_credit

        Unspent advertising credit, in cents.  # noqa: E501
        """
        pass

    def test_get_cbx_claim(self):
        """Test case for get_cbx_claim

        A claim's current state.  # noqa: E501
        """
        pass

    def test_get_cbx_credit(self):
        """Test case for get_cbx_credit

        A seller's wholesale credit line.  # noqa: E501
        """
        pass

    def test_get_cbx_me(self):
        """Test case for get_cbx_me

        Identity check — which merchant this key belongs to, and its terms.  # noqa: E501
        """
        pass

    def test_get_cbx_pool(self):
        """Test case for get_cbx_pool

        Your events-pool balance.  # noqa: E501
        """
        pass

    def test_get_cbx_revenue(self):
        """Test case for get_cbx_revenue

        Operator revenue accrued and not yet withdrawn.  # noqa: E501
        """
        pass

    def test_get_cbx_subject_balance(self):
        """Test case for get_cbx_subject_balance

        What a subject holds: pending cents and available CBX.  # noqa: E501
        """
        pass

    def test_get_cbx_subject_balance_by_subject_id(self):
        """Test case for get_cbx_subject_balance_by_subject_id

        All three balances a subject holds.  # noqa: E501
        """
        pass

    def test_get_cbx_subject_spent(self):
        """Test case for get_cbx_subject_spent

        Total CBX a subject has spent in your marketplace.  # noqa: E501
        """
        pass

    def test_get_cbx_subject_stake(self):
        """Test case for get_cbx_subject_stake

        A subject's staking state and spendable balance.  # noqa: E501
        """
        pass

    def test_get_cbx_subject_wallet(self):
        """Test case for get_cbx_subject_wallet

        The verified payout address for a subject, if any.  # noqa: E501
        """
        pass

    def test_get_cbx_treasury(self):
        """Test case for get_cbx_treasury

        Your most recent reserve reconciliation.  # noqa: E501
        """
        pass

    def test_list_cbx_ad_credit_ledger(self):
        """Test case for list_cbx_ad_credit_ledger

        Ad-credit movements, newest first.  # noqa: E501
        """
        pass

    def test_list_cbx_boosts(self):
        """Test case for list_cbx_boosts

        Your funded cashback boosts, newest first.  # noqa: E501
        """
        pass

    def test_list_cbx_campaign_payouts(self):
        """Test case for list_cbx_campaign_payouts

        What a campaign actually paid, with the weight behind each amount.  # noqa: E501
        """
        pass

    def test_list_cbx_campaigns(self):
        """Test case for list_cbx_campaigns

        Your campaigns, newest first.  # noqa: E501
        """
        pass

    def test_list_cbx_disbursement_progress(self):
        """Test case for list_cbx_disbursement_progress

        How close each rule is to firing — the public counter.  # noqa: E501
        """
        pass

    def test_list_cbx_disbursement_rules(self):
        """Test case for list_cbx_disbursement_rules

        Threshold rules that fire community distributions.  # noqa: E501
        """
        pass

    def test_list_cbx_earn_tiers(self):
        """Test case for list_cbx_earn_tiers

        Earn terms on offer — longer maturation, higher rate.  # noqa: E501
        """
        pass

    def test_list_cbx_redemption_services(self):
        """Test case for list_cbx_redemption_services

        Services payable in CBX, and the discount each carries.  # noqa: E501
        """
        pass

    def test_list_cbx_stake_tiers(self):
        """Test case for list_cbx_stake_tiers

        Staking tiers — what locking tokens buys.  # noqa: E501
        """
        pass

    def test_list_cbx_subject_grants(self):
        """Test case for list_cbx_subject_grants

        Live grants, soonest-expiring first.  # noqa: E501
        """
        pass

    def test_list_cbx_subject_ledger(self):
        """Test case for list_cbx_subject_ledger

        A subject's CBX ledger, newest first.  # noqa: E501
        """
        pass

    def test_list_cbx_wallet_payment_review(self):
        """Test case for list_cbx_wallet_payment_review

        Payments held for a human — the ops queue.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
