"""
    Crossly Seller API

    The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import crossly
from crossly.api.sourcing_api import SourcingApi  # noqa: E501


class TestSourcingApi(unittest.TestCase):
    """SourcingApi unit test stubs"""

    def setUp(self):
        self.api = SourcingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_sourcing_receipt(self):
        """Test case for create_sourcing_receipt

        Append a parsed receipt to the sourcing ledger.  # noqa: E501
        """
        pass

    def test_get_sourcing_receipt(self):
        """Test case for get_sourcing_receipt

        List parsed sourcing receipts in this user's ledger.  # noqa: E501
        """
        pass

    def test_list_sourcing_demand(self):
        """Test case for list_sourcing_demand

        Items buyers looked for on other sites that Crossly did not have.  # noqa: E501
        """
        pass

    def test_list_sourcing_demand_mine(self):
        """Test case for list_sourcing_demand_mine

        Unmet buyer demand for items you hold or have sold before.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
