"""
    Crossly Seller API

    The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import crossly
from crossly.api.payout_api import PayoutApi  # noqa: E501


class TestPayoutApi(unittest.TestCase):
    """PayoutApi unit test stubs"""

    def setUp(self):
        self.api = PayoutApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_payout_estimate(self):
        """Test case for get_payout_estimate

        What one platform nets at a given price, after fees and shipping.  # noqa: E501
        """
        pass

    def test_get_payout_gross_for_net(self):
        """Test case for get_payout_gross_for_net

        The gross price needed to clear a target net on one platform.  # noqa: E501
        """
        pass

    def test_list_payout_compare(self):
        """Test case for list_payout_compare

        Rank platforms by what they net at a given price. Defaults to connected ones.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
