"""
    Crossly Seller API

    The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import crossly
from crossly.api.offers_api import OffersApi  # noqa: E501


class TestOffersApi(unittest.TestCase):
    """OffersApi unit test stubs"""

    def setUp(self):
        self.api = OffersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_offer_respond(self):
        """Test case for create_offer_respond

        Accept, decline, or counter a buyer offer on a Crossly marketplace listing.  # noqa: E501
        """
        pass

    def test_get_offer(self):
        """Test case for get_offer

        List buyer offers on your Crossly marketplace listings, including bundles.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
