"""
    Crossly Seller API

    The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import crossly
from crossly.api.taxonomy_api import TaxonomyApi  # noqa: E501


class TestTaxonomyApi(unittest.TestCase):
    """TaxonomyApi unit test stubs"""

    def setUp(self):
        self.api = TaxonomyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_taxonomy_category(self):
        """Test case for get_taxonomy_category

        Categories for a platform. Default is top-level; pass `?parent=<categoryId>` to drill down one level (supported on cookie platforms whose recipe returns flat parent_id-linked rows).  # noqa: E501
        """
        pass

    def test_get_taxonomy_category_aspect(self):
        """Test case for get_taxonomy_category_aspect

        Item-specific aspects (eBay) / properties (Etsy) / hard-coded enums (cookie platforms) for a category.  # noqa: E501
        """
        pass

    def test_get_taxonomy_category_children(self):
        """Test case for get_taxonomy_category_children

        Direct children of a category node.  # noqa: E501
        """
        pass

    def test_get_taxonomy_required_field(self):
        """Test case for get_taxonomy_required_field

        Normalized field schema the seller needs to fill before crossposting to this platform. Combines master fields (title/description/price/condition) with platform-specific overrides.  # noqa: E501
        """
        pass

    def test_list_taxonomy_suggest(self):
        """Test case for list_taxonomy_suggest

        Reverse lookup — suggest categories matching a search phrase. eBay-only today.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
