"""
    Crossly Seller API

    The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import crossly
from crossly.model.get_inbox_conversation_message_response_messages import GetInboxConversationMessageResponseMessages
globals()['GetInboxConversationMessageResponseMessages'] = GetInboxConversationMessageResponseMessages
from crossly.model.get_inbox_conversation_message_response import GetInboxConversationMessageResponse


class TestGetInboxConversationMessageResponse(unittest.TestCase):
    """GetInboxConversationMessageResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetInboxConversationMessageResponse(self):
        """Test GetInboxConversationMessageResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetInboxConversationMessageResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
