"""
    Crossly Seller API

    The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import crossly
from crossly.api.activity_api import ActivityApi  # noqa: E501


class TestActivityApi(unittest.TestCase):
    """ActivityApi unit test stubs"""

    def setUp(self):
        self.api = ActivityApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_action_log(self):
        """Test case for get_action_log

        Get one action-log event by id (ownership-checked).  # noqa: E501
        """
        pass

    def test_get_action_log_facet(self):
        """Test case for get_action_log_facet

        Distinct platforms / actions / categories present in the caller's action log (last 90 days) — powers filter dropdowns before you query.  # noqa: E501
        """
        pass

    def test_list_action_log(self):
        """Test case for list_action_log

        List action-log events — the semantic \"what happened\" record of every user + platform action. Filter by platform / action / category / status / source / target, and a since/until created_at window.  # noqa: E501
        """
        pass

    def test_list_action_log_calls(self):
        """Test case for list_action_log_calls

        The outbound platform HTTP calls under an event (oldest first) — url, method, status, latency, redacted request/response bodies, proxy + recipe/hash. Answers \"what was sent / what went wrong\".  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
