"""
    Crossly Seller API

    The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import crossly
from crossly.api.reference_api import ReferenceApi  # noqa: E501


class TestReferenceApi(unittest.TestCase):
    """ReferenceApi unit test stubs"""

    def setUp(self):
        self.api = ReferenceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_brand(self):
        """Test case for get_brand

        Search the Crossly brand index. Returns up to 50 matches.  # noqa: E501
        """
        pass

    def test_get_category(self):
        """Test case for get_category

        List Crossly's canonical category tree.  # noqa: E501
        """
        pass

    def test_get_department(self):
        """Test case for get_department

        Search the eBay-sourced \"Department\" item-specific values.  # noqa: E501
        """
        pass

    def test_get_gender(self):
        """Test case for get_gender

        Search the eBay-sourced \"Gender\" item-specific values.  # noqa: E501
        """
        pass

    def test_get_pattern(self):
        """Test case for get_pattern

        Search the eBay-sourced \"Pattern\" item-specific values.  # noqa: E501
        """
        pass

    def test_get_size_system(self):
        """Test case for get_size_system

        Search the Poshmark + Vestiaire size-system union (US/UK/EU/AU/FR/KR).  # noqa: E501
        """
        pass

    def test_get_style(self):
        """Test case for get_style

        Search the eBay-sourced \"Style\" item-specific values.  # noqa: E501
        """
        pass

    def test_get_type(self):
        """Test case for get_type

        Search the eBay-sourced \"Type\" item-specific values.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
