"""
    Crossly Seller API

    The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import crossly
from crossly.api.pat_api import PATApi  # noqa: E501


class TestPATApi(unittest.TestCase):
    """PATApi unit test stubs"""

    def setUp(self):
        self.api = PATApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_pat(self):
        """Test case for create_pat

        Mint a new PAT. Full token returned ONCE — store it on the client.  # noqa: E501
        """
        pass

    def test_delete_pat(self):
        """Test case for delete_pat

        Revoke a PAT by id.  # noqa: E501
        """
        pass

    def test_get_pat_scope(self):
        """Test case for get_pat_scope

        List the canonical scope catalog.  # noqa: E501
        """
        pass

    def test_list_pat(self):
        """Test case for list_pat

        List the caller's PATs (preview only).  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
