"""
    Crossly Seller API

    The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import crossly
from crossly.api.magic_api import MagicApi  # noqa: E501


class TestMagicApi(unittest.TestCase):
    """MagicApi unit test stubs"""

    def setUp(self):
        self.api = MagicApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_magic_scan(self):
        """Test case for create_magic_scan

        Run a Magic List image scan.  # noqa: E501
        """
        pass

    def test_create_magic_scan_synthesize(self):
        """Test case for create_magic_scan_synthesize

        Synthesize a draft from confirmed matches.  # noqa: E501
        """
        pass

    def test_get_magic_draft(self):
        """Test case for get_magic_draft

        Get a synthesized Magic List draft.  # noqa: E501
        """
        pass

    def test_list_magic_recent(self):
        """Test case for list_magic_recent

        Recent Magic List scans for this seller.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
