"""
    Crossly Seller API

    The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import crossly
from crossly.model.get_automation_rule_export_response_action import GetAutomationRuleExportResponseAction
from crossly.model.get_automation_rule_export_response_condition import GetAutomationRuleExportResponseCondition
from crossly.model.get_automation_rule_export_response_metadata import GetAutomationRuleExportResponseMetadata
globals()['GetAutomationRuleExportResponseAction'] = GetAutomationRuleExportResponseAction
globals()['GetAutomationRuleExportResponseCondition'] = GetAutomationRuleExportResponseCondition
globals()['GetAutomationRuleExportResponseMetadata'] = GetAutomationRuleExportResponseMetadata
from crossly.model.get_automation_rule_export_response_recipes import GetAutomationRuleExportResponseRecipes


class TestGetAutomationRuleExportResponseRecipes(unittest.TestCase):
    """GetAutomationRuleExportResponseRecipes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetAutomationRuleExportResponseRecipes(self):
        """Test GetAutomationRuleExportResponseRecipes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetAutomationRuleExportResponseRecipes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
