"""
    Crossly Seller API

    The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import crossly
from crossly.model.create_buyer_activity_response_match_offer import CreateBuyerActivityResponseMatchOffer
from crossly.model.get_catalog_lookup_response_catalog import GetCatalogLookupResponseCatalog
globals()['CreateBuyerActivityResponseMatchOffer'] = CreateBuyerActivityResponseMatchOffer
globals()['GetCatalogLookupResponseCatalog'] = GetCatalogLookupResponseCatalog
from crossly.model.create_buyer_activity_response_match import CreateBuyerActivityResponseMatch


class TestCreateBuyerActivityResponseMatch(unittest.TestCase):
    """CreateBuyerActivityResponseMatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateBuyerActivityResponseMatch(self):
        """Test CreateBuyerActivityResponseMatch"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateBuyerActivityResponseMatch()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
