"""
    Crossly Seller API

    The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import crossly
from crossly.model.get_spatial_public_response_items import GetSpatialPublicResponseItems
from crossly.model.get_spatial_public_response_profile import GetSpatialPublicResponseProfile
from crossly.model.get_spatial_public_response_scene import GetSpatialPublicResponseScene
from crossly.model.get_spatial_public_response_solved import GetSpatialPublicResponseSolved
from crossly.model.get_spatial_public_response_stats import GetSpatialPublicResponseStats
globals()['GetSpatialPublicResponseItems'] = GetSpatialPublicResponseItems
globals()['GetSpatialPublicResponseProfile'] = GetSpatialPublicResponseProfile
globals()['GetSpatialPublicResponseScene'] = GetSpatialPublicResponseScene
globals()['GetSpatialPublicResponseSolved'] = GetSpatialPublicResponseSolved
globals()['GetSpatialPublicResponseStats'] = GetSpatialPublicResponseStats
from crossly.model.get_spatial_public_response import GetSpatialPublicResponse


class TestGetSpatialPublicResponse(unittest.TestCase):
    """GetSpatialPublicResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetSpatialPublicResponse(self):
        """Test GetSpatialPublicResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetSpatialPublicResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
