"""
    Crossly Seller API

    The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from crossly.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from crossly.exceptions import ApiAttributeError


def lazy_import():
    from crossly.model.list_imports_item_filters import ListImportsItemFilters
    globals()['ListImportsItemFilters'] = ListImportsItemFilters


class ListImportsItem(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'id': (str,),  # noqa: E501
            'created_at': (datetime,),  # noqa: E501
            'user_id': (str,),  # noqa: E501
            'status': (str,),  # noqa: E501
            'platform': (str,),  # noqa: E501
            'import_mode': (str,),  # noqa: E501
            'include_inactive': (bool,),  # noqa: E501
            'merge_into_existing_listing': (bool,),  # noqa: E501
            'merge_into_existing_inventory': (bool,),  # noqa: E501
            'total_count': (float,),  # noqa: E501
            'imported_count': (float,),  # noqa: E501
            'skipped_count': (float,),  # noqa: E501
            'error_count': (float,),  # noqa: E501
            'last_error': (str, none_type,),  # noqa: E501
            'started_at': (datetime, none_type,),  # noqa: E501
            'filters': (ListImportsItemFilters,),  # noqa: E501
            'finished_at': (datetime, none_type,),  # noqa: E501
            'batch_id': (str, none_type,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'id': 'id',  # noqa: E501
        'created_at': 'createdAt',  # noqa: E501
        'user_id': 'userId',  # noqa: E501
        'status': 'status',  # noqa: E501
        'platform': 'platform',  # noqa: E501
        'import_mode': 'importMode',  # noqa: E501
        'include_inactive': 'includeInactive',  # noqa: E501
        'merge_into_existing_listing': 'mergeIntoExistingListing',  # noqa: E501
        'merge_into_existing_inventory': 'mergeIntoExistingInventory',  # noqa: E501
        'total_count': 'totalCount',  # noqa: E501
        'imported_count': 'importedCount',  # noqa: E501
        'skipped_count': 'skippedCount',  # noqa: E501
        'error_count': 'errorCount',  # noqa: E501
        'last_error': 'lastError',  # noqa: E501
        'started_at': 'startedAt',  # noqa: E501
        'filters': 'filters',  # noqa: E501
        'finished_at': 'finishedAt',  # noqa: E501
        'batch_id': 'batchId',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, id, created_at, user_id, status, platform, import_mode, include_inactive, merge_into_existing_listing, merge_into_existing_inventory, total_count, imported_count, skipped_count, error_count, *args, **kwargs):  # noqa: E501
        """ListImportsItem - a model defined in OpenAPI

        Args:
            id (str):
            created_at (datetime):
            user_id (str):
            status (str):
            platform (str):
            import_mode (str):
            include_inactive (bool):
            merge_into_existing_listing (bool):
            merge_into_existing_inventory (bool):
            total_count (float):
            imported_count (float):
            skipped_count (float):
            error_count (float):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            last_error (str, none_type): [optional]  # noqa: E501
            started_at (datetime, none_type): [optional]  # noqa: E501
            filters (ListImportsItemFilters): [optional]  # noqa: E501
            finished_at (datetime, none_type): [optional]  # noqa: E501
            batch_id (str, none_type): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.id = id
        self.created_at = created_at
        self.user_id = user_id
        self.status = status
        self.platform = platform
        self.import_mode = import_mode
        self.include_inactive = include_inactive
        self.merge_into_existing_listing = merge_into_existing_listing
        self.merge_into_existing_inventory = merge_into_existing_inventory
        self.total_count = total_count
        self.imported_count = imported_count
        self.skipped_count = skipped_count
        self.error_count = error_count
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, id, created_at, user_id, status, platform, import_mode, include_inactive, merge_into_existing_listing, merge_into_existing_inventory, total_count, imported_count, skipped_count, error_count, *args, **kwargs):  # noqa: E501
        """ListImportsItem - a model defined in OpenAPI

        Args:
            id (str):
            created_at (datetime):
            user_id (str):
            status (str):
            platform (str):
            import_mode (str):
            include_inactive (bool):
            merge_into_existing_listing (bool):
            merge_into_existing_inventory (bool):
            total_count (float):
            imported_count (float):
            skipped_count (float):
            error_count (float):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            last_error (str, none_type): [optional]  # noqa: E501
            started_at (datetime, none_type): [optional]  # noqa: E501
            filters (ListImportsItemFilters): [optional]  # noqa: E501
            finished_at (datetime, none_type): [optional]  # noqa: E501
            batch_id (str, none_type): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.id = id
        self.created_at = created_at
        self.user_id = user_id
        self.status = status
        self.platform = platform
        self.import_mode = import_mode
        self.include_inactive = include_inactive
        self.merge_into_existing_listing = merge_into_existing_listing
        self.merge_into_existing_inventory = merge_into_existing_inventory
        self.total_count = total_count
        self.imported_count = imported_count
        self.skipped_count = skipped_count
        self.error_count = error_count
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
